### ISSUE TITLE
Feature request. Terminal toggle from vs code command pallets.

### ISSUE THREAD

**Issue by arshappleid** [YaduAhuja/Code-Builder#3]
Can you add a toggle switch in the vs code command pallete (ctrl+shift+p) , that switches between run in external terminal, and run in vs code terminal settings.

**Comment by YaduAhuja** [comment]
Its because of the checks which are being done when the extension loads I am working on it right now. It will be fixed till next week.

**Comment by arshapplied** [comment]
Hey do you think you can tell me how i can run java files, with external libraries. Using this extension. I am using the basic java extension recommended by microsoft to run java code.  Then i add the library file to the referenced libraries folder (from java projects). My question is since i am doing all this , and running the file using this terminal extension, does it remember that i imported a library jar file, using the java projects section.

I do not incur this problem with python, since in python i can just setup up environment variables.

**Comment by YaduAhuja** [comment]
There is no functionality to Dynamically run External Libraries with Code Builder as of now.
